apiVersion: apps/v1
kind: Deployment
metadata:
  name: Maintenance
  labels:
    app: Maintenance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Maintenance
  template:
    metadata:
      labels:
        app: Maintenance
    spec:
      containers:
        - name: Maintenance
          image: "username/Maintenance:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
